heat_template_version: 2013-05-23

description: |
  This is a Heat template to deploy a single Linux server running Vesta Control
  Panel

parameters:

  server_hostname:
    description: Server Name
    type: string
    default: vesta
    constraints:
    - length:
        min: 1
        max: 64
    - allowed_pattern: "^[a-zA-Z][a-zA-Z0-9-]*$"
      description: |
        Must begin with a letter and contain only alphanumeric characters.

  image:
    description: Server Image
    type: string
    default: Ubuntu 12.04 LTS (Precise Pangolin)
    constraints:
    - allowed_values:
      - CentOS 6.5
      - CentOS 6.5 (PVHVM)
      - Debian 7 (Wheezy) (PVHVM)
      - Ubuntu 12.04 LTS (Precise Pangolin)
      - Ubuntu 12.04 LTS (Precise Pangolin) (PVHVM)
      description: Must be a supported operating system.

  flavor:
    description: Rackspace Cloud Server flavor
    type: string
    default: 2 GB Performance
    constraints:
    - allowed_values:
      - 1 GB Performance
      - 2 GB Performance
      - 4 GB Performance
      - 8 GB Performance
      - 15 GB Performance
      - 30 GB Performance
      - 1GB Standard Instance
      - 2GB Standard Instance
      - 4GB Standard Instance
      - 8GB Standard Instance
      - 15GB Standard Instance
      - 30GB Standard Instance
      description: |
        Must be a valid Rackspace Cloud Server flavor for the region you have
        selected to deploy into.

  ssh_keypair_name:
    description: Nova keypair name for ssh access to the server
    type: string
    constraints:
    - allowed_pattern: "^(.){1,64}$"
      description: "Must be shorter than 64 characters or fewer."

  vesta_email_address:
    description: Email address to configure as the administrative user
    type: string
    default: root@localhost

  vesta_admin_password:
    description: Admin Password to use with Vesta
    type: string

resources:

  ssh_key:
    type: "OS::Nova::KeyPair"
    properties:
      name: { get_param: ssh_keypair_name }
      save_private_key: true

  vesta_server:
    type: "Rackspace::Cloud::Server"
    properties:
      name: { get_param: server_hostname }
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_resource: ssh_key }

  vesta_setup:
    type: "OS::Heat::ChefSolo"
    depends_on: vesta_server
    properties:
      username: root
      private_key: { get_attr: [ssh_key, private_key] }
      host: { get_attr: [vesta_server, accessIPv4] }
      Berksfile: |
        site :opscode

        cookbook 'vesta',
          :git => 'https://github.com/brint/cookbook-vesta'
      node:
        vesta:
          email: { get_param: vesta_email_address }
          admin_password: { get_param: vesta_admin_password }
        run_list: ["recipe[vesta]",
                   "recipe[vesta::firewall]"]

outputs:
  private_key:
    value: { get_attr: [ssh_key, private_key] }

  server_ip:
    value: { get_attr: [vesta_server, accessIPv4] }

  admin_password:
    value: { get_param: vesta_admin_password }

  vesta_url:
    value:
      str_replace:
        template: "https://%server_ip%:8083"
        params:
          "%server_ip%": { get_attr: [vesta_server, accessIPv4] }
